services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backlinks_db
    ports:
      - "5432:5432"

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: database
      PORT: 3000
    depends_on:
      - database